### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by madhubhasha** [mooniak/animager#18]
cp: cannot stat ‘profiles/.prof’: No such file or directory
[sudo] password for mooniak: 
cp: cannot stat ‘.py’: No such file or directory
/home/mooniak/Downloads/animager-master/src/install.sh: 17: /home/mooniak/Downloads/animager-master/src/install.sh: g++: not found
cp: omitting directory ‘animager’

**Comment by lpsandaruwan** [comment]
I recommend you to do the installation manually, I will come up with a solution soon. Follow these steps.

You need to install the C++ compiler. To install it,
sudo apt-get install g++

To clean the previous buggy installation,
sudo rm -r /opt/animager /usr/bin/animager
rm -r ~/animager

cd into the src folder and,
mkdir -p ~/animager ~/animager/morph-cache ~/animager/profiles
cp -r profiles/*.prof ~/animager/profiles/
sudo mkdir -p /opt/animager
g++ cmd.cpp -o animager
sudo cp -r *.py /opt/animager/
sudo cp animager /usr/bin/
