### ISSUE TITLE
error saving files

### ISSUE THREAD

**Issue by madhubhasha** [mooniak/animager#19]
after this the destination folder is empty. no video or images

Keep temporary image files ? (y/n) y
Traceback (most recent call last):
  File "/opt/animager/process.py", line 92, in <module>
    main( sys.argv )
  File "/opt/animager/process.py", line 75, in main
    keepTemp = input( '\nKeep temporary image files ? (y/n) ' )
  File "<string>", line 1, in <module>
NameError: name 'y' is not defined

**Comment by pathumego** [comment]
@lpsandaruwan  this is the same error i get in ubuntu

**Comment by lpsandaruwan** [comment]
what is the output of,
python --version                  ?

**Comment by lpsandaruwan** [comment]
Issue is fixed. try re installing Animager.

**Comment by pathumego** [comment]
#24 Fixed this.
